# Configuración de conexión MySQL en la nube
db.host=sql305.infinityfree.com
db.port=3306
db.database=if0_39710241_reparsoftdb
db.user=if0_39710241
db.password=VcWoxuGhtAr

# Parámetros extra opcionales (SSL, zona horaria, etc.)
db.options=useSSL=false&serverTimezone=UTC
