# Configuración de conexión MySQL en la nube
db.host=bzksoiq69diy5ibaip59-mysql.services.clever-cloud.com
db.port=3306
db.database=bzksoiq69diy5ibaip59
db.user=u89981wx8faixfvz 	
db.password=PRYdxXIulQftSTSjAkbl

# Parámetros extra opcionales (SSL, zona horaria, etc.)
db.options=useSSL=false&serverTimezone=UTC
